import { EventType, HistoricalEvent } from "../types";

export const MOCK_EVENTS: HistoricalEvent[] = [
    // --- Cosmic & Prehistory ---
    {
        id: "big-bang",
        type: EventType.ERA,
        title: "The Beginning",
        year: -13800000000,
        yearDisplay: "13.8 BYA",
        description: "The cosmic dawn of the universe.",
        importance: 10,
        tags: ["Cosmic", "Space", "Science"],
        imageUrl: "https://picsum.photos/seed/bigbang/200/200"
    },
    {
        id: "earth-formed",
        type: EventType.EVENT,
        title: "Formation of Earth",
        year: -4540000000,
        yearDisplay: "4.54 BYA",
        description: "Earth forms from the accretion of the solar nebula.",
        importance: 8,
        tags: ["Cosmic", "Earth", "Space", "Science"],
        imageUrl: "https://picsum.photos/seed/earth/200/200"
    },
    {
        id: "life-begins",
        type: EventType.EVENT,
        title: "First Life",
        year: -3500000000,
        yearDisplay: "3.5 BYA",
        description: "Simple single-celled organisms (prokaryotes) appear.",
        importance: 7,
        tags: ["Biology", "Science"],
    },
    {
        id: "dinosaurs-extinct",
        type: EventType.EVENT,
        title: "K-Pg Extinction Event",
        year: -66000000,
        yearDisplay: "66 MYA",
        description: "Asteroid impact wipes out non-avian dinosaurs.",
        importance: 9,
        tags: ["Prehistory", "Earth", "Disaster", "Science"],
    },
    {
        id: "homo-sapiens",
        type: EventType.EVENT,
        title: "Homo Sapiens Emerge",
        year: -300000,
        yearDisplay: "300,000 BC",
        description: "Anatomically modern humans evolve in Africa.",
        importance: 9,
        tags: ["Anthropology", "Biology", "Science"],
    },
    {
        id: "agriculture",
        type: EventType.EVENT,
        title: "Agricultural Revolution",
        year: -10000,
        yearDisplay: "10,000 BC",
        description: "Humans begin farming and domesticating animals, leading to settled societies.",
        importance: 9,
        tags: ["Society", "Technology", "Innovation"],
        imageUrl: "https://picsum.photos/seed/farm/800/600"
    },
    {
        id: "wheel",
        type: EventType.SUB_EVENT,
        title: "Invention of the Wheel",
        year: -3500,
        yearDisplay: "3500 BC",
        description: "The wheel is invented in Mesopotamia, revolutionizing transport.",
        importance: 6,
        tags: ["Technology", "Innovation"],
    },
    {
        id: "writing",
        type: EventType.SUB_EVENT,
        title: "Invention of Writing",
        year: -3200,
        yearDisplay: "3200 BC",
        description: "Cuneiform script emerges in Sumer.",
        importance: 6,
        tags: ["Culture", "Technology", "Art"],
    },
    {
        id: "pyramids",
        type: EventType.EVENT,
        title: "Great Pyramid of Giza",
        year: -2560,
        yearDisplay: "2560 BC",
        description: "Completion of the Great Pyramid for Pharaoh Khufu.",
        importance: 8,
        tags: ["Architecture", "Egypt", "Art", "Culture"],
        imageUrl: "https://picsum.photos/seed/pyramid/600/400"
    },

    // --- Classical Era ---
    {
        id: "classical-era",
        type: EventType.ERA,
        title: "Classical Antiquity",
        year: -800,
        yearDisplay: "800 BC - 500 AD",
        description: "The era of Greek and Roman dominance in the Mediterranean.",
        importance: 10,
        tags: ["History", "Art", "Culture", "Politics"],
    },
    {
        id: "rome-founded",
        type: EventType.EVENT,
        title: "Founding of Rome",
        year: -753,
        yearDisplay: "753 BC",
        description: "Legendary founding of Rome by Romulus and Remus.",
        importance: 7,
        parentId: "classical-era",
        tags: ["Politics", "Rome", "History"],
        imageUrl: "https://picsum.photos/seed/rome/800/400"
    },
    {
        id: "buddhism",
        type: EventType.SUB_EVENT,
        title: "Birth of Buddhism",
        year: -563,
        yearDisplay: "563 BC",
        description: "Siddhartha Gautama (The Buddha) is born in Lumbini.",
        importance: 5,
        parentId: "classical-era",
        tags: ["Religion", "Culture", "Philosophy"],
    },
    {
        id: "democracy",
        type: EventType.SUB_EVENT,
        title: "Athenian Democracy",
        year: -508,
        yearDisplay: "508 BC",
        description: "Cleisthenes introduces democratic reforms in Athens.",
        importance: 6,
        parentId: "classical-era",
        tags: ["Politics", "Greece", "Society"],
    },
    {
        id: "alexander",
        type: EventType.EVENT,
        title: "Alexander the Great",
        year: -336,
        yearDisplay: "336 BC",
        description: "Alexander becomes King of Macedon and begins his conquests.",
        importance: 8,
        parentId: "classical-era",
        tags: ["War", "Greece", "Politics"],
    },
    {
        id: "great-wall",
        type: EventType.EVENT,
        title: "Great Wall of China",
        year: -221,
        yearDisplay: "221 BC",
        description: "Qin Shi Huang begins unifying the walls of China.",
        importance: 8,
        tags: ["China", "Architecture", "Technology"],
    },
    {
        id: "caesar-death",
        type: EventType.EVENT,
        title: "Assassination of Julius Caesar",
        year: -44,
        yearDisplay: "44 BC",
        dateDisplay: "March 15th",
        description: "Julius Caesar is stabbed to death in the Senate of Rome.",
        importance: 8,
        parentId: "classical-era",
        tags: ["Politics", "Rome", "War"],
        imageUrl: "https://picsum.photos/seed/caesar/800/400"
    },
    {
        id: "pompeii",
        type: EventType.SUB_EVENT,
        title: "Eruption of Mount Vesuvius",
        year: 79,
        yearDisplay: "79 AD",
        description: "Pompeii and Herculaneum are destroyed by volcanic ash.",
        importance: 5,
        parentId: "classical-era",
        tags: ["Disaster", "Rome", "Earth"],
    },
    
    // --- Middle Ages ---
    {
        id: "middle-ages",
        type: EventType.ERA,
        title: "The Middle Ages",
        year: 476,
        yearDisplay: "476 - 1450",
        description: "Period from the fall of Rome to the Renaissance.",
        importance: 10,
        tags: ["History", "Europe", "Religion", "Culture"],
    },
    {
        id: "rome-fall",
        type: EventType.EVENT,
        title: "Fall of Western Rome",
        year: 476,
        yearDisplay: "476 AD",
        description: "Romulus Augustulus is deposed, marking the end of the Western Roman Empire.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["Politics", "Rome"],
    },
    {
        id: "islam-founding",
        type: EventType.EVENT,
        title: "Founding of Islam",
        year: 610,
        yearDisplay: "610 AD",
        description: "Muhammad receives his first revelation.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["Religion", "Culture"],
    },
    {
        id: "charlemagne",
        type: EventType.SUB_EVENT,
        title: "Charlemagne Crowned",
        year: 800,
        yearDisplay: "800 AD",
        description: "Charlemagne is crowned Emperor of the Romans.",
        importance: 6,
        parentId: "middle-ages",
        tags: ["Politics", "Europe"],
    },
    {
        id: "gunpowder",
        type: EventType.SUB_EVENT,
        title: "Invention of Gunpowder",
        year: 850,
        yearDisplay: "850 AD",
        description: "Chinese alchemists discover gunpowder.",
        importance: 6,
        tags: ["Technology", "War", "Innovation", "Science"],
    },
    {
        id: "hastings",
        type: EventType.EVENT,
        title: "Battle of Hastings",
        year: 1066,
        yearDisplay: "1066",
        description: "William the Conqueror defeats King Harold II.",
        importance: 8,
        parentId: "middle-ages",
        tags: ["War", "UK"],
    },
    {
        id: "universities",
        type: EventType.SUB_EVENT,
        title: "First University",
        year: 1088,
        yearDisplay: "1088",
        description: "University of Bologna is founded, the oldest in the world.",
        importance: 4,
        parentId: "middle-ages",
        tags: ["Education", "Culture", "Science"],
    },
    {
        id: "genghis",
        type: EventType.EVENT,
        title: "Mongol Empire",
        year: 1206,
        yearDisplay: "1206",
        description: "Genghis Khan unites the Mongol tribes.",
        importance: 8,
        parentId: "middle-ages",
        tags: ["War", "Asia"],
    },
    {
        id: "magna-carta",
        type: EventType.SUB_EVENT,
        title: "Magna Carta",
        year: 1215,
        yearDisplay: "1215",
        description: "King John of England signs the Magna Carta.",
        importance: 6,
        parentId: "middle-ages",
        tags: ["Politics", "Law"],
    },
    {
        id: "black-death",
        type: EventType.EVENT,
        title: "The Black Death",
        year: 1347,
        yearDisplay: "1347",
        description: "Plague devastates Europe, killing estimated 30-60% of population.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["Health", "Disaster", "Science"],
    },

    // --- Early Modern ---
    {
        id: "renaissance",
        type: EventType.ERA,
        title: "Early Modern Period",
        year: 1450,
        yearDisplay: "1450 - 1750",
        description: "Renaissance, Reformation, and Age of Discovery.",
        importance: 10,
        tags: ["Art", "Science", "Culture", "Technology"],
    },
    {
        id: "printing-press",
        type: EventType.EVENT,
        title: "Printing Press",
        year: 1440,
        yearDisplay: "1440",
        description: "Johannes Gutenberg invents the movable type printing press.",
        importance: 9,
        parentId: "renaissance",
        tags: ["Technology", "Innovation", "Culture", "Literature"],
    },
    {
        id: "columbus",
        type: EventType.EVENT,
        title: "Voyage of Columbus",
        year: 1492,
        yearDisplay: "1492",
        description: "Christopher Columbus arrives in the Americas.",
        importance: 8,
        parentId: "renaissance",
        tags: ["Exploration", "History"],
    },
    {
        id: "da-vinci",
        type: EventType.SUB_EVENT,
        title: "Mona Lisa Painted",
        year: 1503,
        yearDisplay: "1503",
        description: "Leonardo da Vinci begins painting the Mona Lisa.",
        importance: 5,
        parentId: "renaissance",
        tags: ["Art", "Culture"],
    },
    {
        id: "reformation",
        type: EventType.EVENT,
        title: "The Reformation",
        year: 1517,
        yearDisplay: "1517",
        description: "Martin Luther posts his 95 Theses.",
        importance: 8,
        parentId: "renaissance",
        tags: ["Religion", "Culture"],
    },
    {
        id: "copernicus",
        type: EventType.SUB_EVENT,
        title: "Heliocentrism",
        year: 1543,
        yearDisplay: "1543",
        description: "Copernicus publishes De revolutionibus orbium coelestium.",
        importance: 6,
        parentId: "renaissance",
        tags: ["Science", "Space"],
    },
    {
        id: "shakespeare",
        type: EventType.SUB_EVENT,
        title: "Shakespeare's Peak",
        year: 1600,
        yearDisplay: "1600",
        description: "William Shakespeare writes Hamlet.",
        importance: 6,
        parentId: "renaissance",
        tags: ["Literature", "Art", "Culture"],
    },
    {
        id: "galileo",
        type: EventType.SUB_EVENT,
        title: "Galileo's Telescope",
        year: 1609,
        yearDisplay: "1609",
        description: "Galileo demonstrates his telescope to the Venetian senate.",
        importance: 6,
        parentId: "renaissance",
        tags: ["Science", "Space", "Technology"],
    },
    {
        id: "mayflower",
        type: EventType.SUB_EVENT,
        title: "The Mayflower",
        year: 1620,
        yearDisplay: "1620",
        description: "Pilgrims land at Plymouth Rock.",
        importance: 5,
        parentId: "renaissance",
        tags: ["USA", "History"],
    },
    {
        id: "newton",
        type: EventType.SUB_EVENT,
        title: "Principia Mathematica",
        year: 1687,
        yearDisplay: "1687",
        description: "Isaac Newton publishes laws of motion and gravity.",
        importance: 7,
        parentId: "renaissance",
        tags: ["Science", "Physics"],
    },

    // --- Industrial & Revolution ---
    {
        id: "industrial-rev",
        type: EventType.ERA,
        title: "Age of Revolution",
        year: 1760,
        yearDisplay: "1760 - 1840",
        description: "Industrial revolution and political revolutions in America and France.",
        importance: 10,
        tags: ["Industry", "Politics", "Technology", "Innovation"],
    },
    {
        id: "spinning-jenny",
        type: EventType.EVENT,
        title: "Spinning Jenny",
        year: 1764,
        yearDisplay: "1764",
        description: "James Hargreaves invents the Spinning Jenny.",
        importance: 7,
        parentId: "industrial-rev",
        tags: ["Technology", "Industry", "Innovation"],
        imageUrl: "https://picsum.photos/seed/jenny/200/200"
    },
    {
        id: "steam-engine",
        type: EventType.EVENT,
        title: "Watt Steam Engine",
        year: 1769,
        yearDisplay: "1769",
        description: "James Watt improves the steam engine.",
        importance: 8,
        parentId: "industrial-rev",
        tags: ["Technology", "Innovation", "Power"],
    },
    {
        id: "us-independence",
        type: EventType.EVENT,
        title: "US Declaration of Independence",
        year: 1776,
        yearDisplay: "1776",
        description: "The 13 colonies declare independence from Britain.",
        importance: 9,
        parentId: "industrial-rev",
        tags: ["Politics", "USA"],
    },
    {
        id: "french-rev",
        type: EventType.EVENT,
        title: "French Revolution",
        year: 1789,
        yearDisplay: "1789",
        description: "Storming of the Bastille.",
        importance: 8,
        parentId: "industrial-rev",
        tags: ["Politics", "France"],
    },
    {
        id: "smallpox-vaccine",
        type: EventType.SUB_EVENT,
        title: "First Vaccine",
        year: 1796,
        yearDisplay: "1796",
        description: "Edward Jenner creates the smallpox vaccine.",
        importance: 6,
        parentId: "industrial-rev",
        tags: ["Health", "Science", "Innovation"],
    },
    {
        id: "napoleon",
        type: EventType.SUB_EVENT,
        title: "Napoleon Emperor",
        year: 1804,
        yearDisplay: "1804",
        description: "Napoleon Bonaparte crowns himself Emperor of the French.",
        importance: 6,
        parentId: "industrial-rev",
        tags: ["Politics", "War"],
    },
    {
        id: "train",
        type: EventType.SUB_EVENT,
        title: "First Steam Locomotive",
        year: 1804,
        yearDisplay: "1804",
        description: "Richard Trevithick runs the first full-scale steam locomotive.",
        importance: 6,
        parentId: "industrial-rev",
        tags: ["Technology", "Innovation", "Transport"],
    },
    {
        id: "telegraph",
        type: EventType.SUB_EVENT,
        title: "Electric Telegraph",
        year: 1837,
        yearDisplay: "1837",
        description: "Samuel Morse patents the telegraph.",
        importance: 6,
        parentId: "industrial-rev",
        tags: ["Technology", "Comms", "Innovation"],
    },
    {
        id: "photography",
        type: EventType.SUB_EVENT,
        title: "Daguerreotype",
        year: 1839,
        yearDisplay: "1839",
        description: "Louis Daguerre introduces the first publicly announced photographic process.",
        importance: 5,
        parentId: "industrial-rev",
        tags: ["Art", "Technology", "Innovation"],
    },

    // --- Victorian & Modernizing ---
    {
        id: "victorian-era",
        type: EventType.ERA,
        title: "The Victorian Era",
        year: 1837,
        yearDisplay: "1837 - 1901",
        description: "Pax Britannica and rapid technological advancement.",
        importance: 8,
        tags: ["UK", "Era", "Technology", "Culture"],
    },
    {
        id: "darwin",
        type: EventType.EVENT,
        title: "Origin of Species",
        year: 1859,
        yearDisplay: "1859",
        description: "Charles Darwin publishes his theory of evolution.",
        importance: 8,
        parentId: "victorian-era",
        tags: ["Science", "Biology"],
    },
    {
        id: "civil-war",
        type: EventType.EVENT,
        title: "US Civil War Begins",
        year: 1861,
        yearDisplay: "1861",
        description: "War breaks out between the Union and the Confederacy.",
        importance: 8,
        parentId: "victorian-era",
        tags: ["War", "USA"],
    },
    {
        id: "emancipation",
        type: EventType.SUB_EVENT,
        title: "Emancipation Proclamation",
        year: 1863,
        yearDisplay: "1863",
        description: "Lincoln declares slaves in rebel states to be free.",
        importance: 6,
        parentId: "victorian-era",
        tags: ["Politics", "USA", "Society"],
    },
    {
        id: "telephone",
        type: EventType.SUB_EVENT,
        title: "Telephone Invented",
        year: 1876,
        yearDisplay: "1876",
        description: "Alexander Graham Bell patents the telephone.",
        importance: 7,
        parentId: "victorian-era",
        tags: ["Technology", "Innovation", "Comms"],
    },
    {
        id: "lightbulb",
        type: EventType.EVENT,
        title: "Incandescent Lightbulb",
        year: 1879,
        yearDisplay: "1879",
        description: "Edison creates the first practical lightbulb.",
        importance: 8,
        tags: ["Technology", "Innovation"],
        imageUrl: "https://picsum.photos/seed/lightbulb/400/400"
    },
    {
        id: "car",
        type: EventType.SUB_EVENT,
        title: "First Automobile",
        year: 1886,
        yearDisplay: "1886",
        description: "Karl Benz patents the Motorwagen.",
        importance: 7,
        parentId: "victorian-era",
        tags: ["Technology", "Innovation", "Transport"],
    },
    {
        id: "xray",
        type: EventType.SUB_EVENT,
        title: "X-Rays Discovered",
        year: 1895,
        yearDisplay: "1895",
        description: "Wilhelm Röntgen discovers X-rays.",
        importance: 5,
        parentId: "victorian-era",
        tags: ["Science", "Health"],
    },

    // --- 20th Century: Wars ---
    {
        id: "ww1-era",
        type: EventType.ERA,
        title: "The Great War Era",
        year: 1914,
        yearDisplay: "1914 - 1918",
        description: "The first global industrialized conflict.",
        importance: 10,
        tags: ["War", "Politics", "Technology"],
    },
    {
        id: "flight",
        type: EventType.EVENT,
        title: "First Flight",
        year: 1903,
        yearDisplay: "1903",
        dateDisplay: "Dec 17th",
        description: "Wright Brothers fly at Kitty Hawk.",
        importance: 8,
        tags: ["Technology", "Innovation", "Aviation"],
        imageUrl: "https://picsum.photos/seed/flight/800/400"
    },
    {
        id: "titanic",
        type: EventType.SUB_EVENT,
        title: "Sinking of the Titanic",
        year: 1912,
        yearDisplay: "1912",
        description: "The unsinkable ship hits an iceberg.",
        importance: 6,
        tags: ["Disaster"],
    },
    {
        id: "ford-assembly",
        type: EventType.SUB_EVENT,
        title: "Ford Assembly Line",
        year: 1913,
        yearDisplay: "1913",
        description: "Henry Ford installs the first moving assembly line.",
        importance: 5,
        tags: ["Industry", "Technology", "Innovation"],
    },
    {
        id: "archduke",
        type: EventType.SUB_EVENT,
        title: "Assassination of Archduke Ferdinand",
        year: 1914,
        yearDisplay: "1914",
        dateDisplay: "June 28th",
        description: "The spark that ignited World War I.",
        importance: 6,
        parentId: "ww1-era",
        tags: ["War", "Politics"],
    },
    {
        id: "russian-rev",
        type: EventType.EVENT,
        title: "Russian Revolution",
        year: 1917,
        yearDisplay: "1917",
        description: "Bolsheviks seize power in Russia.",
        importance: 8,
        parentId: "ww1-era",
        tags: ["Politics"],
    },
    {
        id: "flu",
        type: EventType.SUB_EVENT,
        title: "Spanish Flu",
        year: 1918,
        yearDisplay: "1918",
        description: "Deadly influenza pandemic sweeps the globe.",
        importance: 6,
        parentId: "ww1-era",
        tags: ["Health", "Disaster", "Science"],
    },
    {
        id: "suffrage",
        type: EventType.SUB_EVENT,
        title: "US Women's Suffrage",
        year: 1920,
        yearDisplay: "1920",
        description: "19th Amendment guarantees women the right to vote.",
        importance: 6,
        tags: ["Politics", "USA", "Society"],
    },
    {
        id: "penicillin",
        type: EventType.EVENT,
        title: "Discovery of Penicillin",
        year: 1928,
        yearDisplay: "1928",
        description: "Alexander Fleming discovers the first antibiotic.",
        importance: 8,
        tags: ["Health", "Science", "Innovation"],
    },
    {
        id: "stock-crash",
        type: EventType.SUB_EVENT,
        title: "Wall Street Crash",
        year: 1929,
        yearDisplay: "1929",
        description: "Start of the Great Depression.",
        importance: 6,
        tags: ["Economics"],
    },

    // --- WW2 ---
    {
        id: "ww2-era",
        type: EventType.ERA,
        title: "World War II",
        year: 1939,
        yearDisplay: "1939 - 1945",
        description: "Global war between the Allies and Axis powers.",
        importance: 10,
        tags: ["War", "Politics"],
    },
    {
        id: "poland-invasion",
        type: EventType.SUB_EVENT,
        title: "Invasion of Poland",
        year: 1939,
        yearDisplay: "1939",
        dateDisplay: "Sept 1st",
        description: "Germany invades Poland, starting WW2.",
        importance: 6,
        parentId: "ww2-era",
        tags: ["War"],
    },
    {
        id: "pearl-harbor",
        type: EventType.EVENT,
        title: "Attack on Pearl Harbor",
        year: 1941,
        yearDisplay: "1941",
        dateDisplay: "Dec 7th",
        description: "Japan attacks US naval base, bringing US into the war.",
        importance: 8,
        parentId: "ww2-era",
        tags: ["War", "USA"],
    },
    {
        id: "d-day",
        type: EventType.EVENT,
        title: "D-Day Landings",
        year: 1944,
        yearDisplay: "1944",
        dateDisplay: "June 6th",
        description: "Allied forces invade Normandy.",
        importance: 8,
        parentId: "ww2-era",
        tags: ["War"],
    },
    {
        id: "hiroshima",
        type: EventType.EVENT,
        title: "Hiroshima Bombing",
        year: 1945,
        yearDisplay: "1945",
        dateDisplay: "Aug 6th",
        description: "First use of atomic bomb in warfare.",
        importance: 9,
        parentId: "ww2-era",
        tags: ["War", "Technology"],
    },

    // --- Cold War & Modern ---
    {
        id: "cold-war",
        type: EventType.ERA,
        title: "The Cold War Era",
        year: 1947,
        yearDisplay: "1947 - 1991",
        description: "Geopolitical tension between USSR and USA.",
        importance: 10,
        tags: ["Politics", "War", "Science", "Space"],
    },
    {
        id: "dna",
        type: EventType.SUB_EVENT,
        title: "Structure of DNA",
        year: 1953,
        yearDisplay: "1953",
        description: "Watson and Crick identify the double helix.",
        importance: 7,
        tags: ["Science", "Biology", "Innovation"],
    },
    {
        id: "sputnik",
        type: EventType.SUB_EVENT,
        title: "Sputnik 1",
        year: 1957,
        yearDisplay: "1957",
        description: "Soviet Union launches first artificial satellite.",
        importance: 7,
        parentId: "cold-war",
        tags: ["Space", "Technology", "Innovation"],
    },
    {
        id: "civil-rights",
        type: EventType.SUB_EVENT,
        title: "I Have A Dream",
        year: 1963,
        yearDisplay: "1963",
        description: "MLK Jr. delivers historic speech in Washington.",
        importance: 6,
        tags: ["Politics", "USA", "Society", "Culture"],
    },
    {
        id: "moon-landing",
        type: EventType.EVENT,
        title: "Apollo 11 Moon Landing",
        year: 1969,
        yearDisplay: "1969",
        dateDisplay: "July 20th",
        description: "Neil Armstrong steps on the moon.",
        importance: 10,
        parentId: "cold-war",
        tags: ["Space", "Technology", "USA", "Innovation"],
        imageUrl: "https://picsum.photos/seed/moon/800/600",
        sourceUrl: "https://www.nasa.gov/mission_pages/apollo/apollo11.html"
    },
    {
        id: "internet-birth",
        type: EventType.EVENT,
        title: "Birth of the Internet",
        year: 1983,
        yearDisplay: "1983",
        description: "ARPANET adopts TCP/IP.",
        importance: 8,
        tags: ["Technology", "Innovation", "Comms"],
    },
    {
        id: "chernobyl",
        type: EventType.SUB_EVENT,
        title: "Chernobyl Disaster",
        year: 1986,
        yearDisplay: "1986",
        description: "Nuclear reactor melts down in Ukraine.",
        importance: 6,
        tags: ["Disaster", "Technology"],
    },
    {
        id: "berlin-wall",
        type: EventType.EVENT,
        title: "Fall of Berlin Wall",
        year: 1989,
        yearDisplay: "1989",
        description: "Symbol of Cold War collapses.",
        importance: 8,
        parentId: "cold-war",
        tags: ["Politics"],
    },
    {
        id: "web",
        type: EventType.EVENT,
        title: "World Wide Web",
        year: 1991,
        yearDisplay: "1991",
        description: "Tim Berners-Lee releases the web to the public.",
        importance: 9,
        tags: ["Technology", "Innovation", "Comms"],
    },
    {
        id: "dolly",
        type: EventType.SUB_EVENT,
        title: "Dolly the Sheep",
        year: 1996,
        yearDisplay: "1996",
        description: "First mammal cloned from an adult somatic cell.",
        importance: 5,
        tags: ["Science", "Biology", "Innovation"],
    },

    // --- 21st Century ---
    {
        id: "info-age",
        type: EventType.ERA,
        title: "The Information Age",
        year: 2000,
        yearDisplay: "2000 - Present",
        description: "The digital revolution and interconnected world.",
        importance: 10,
        tags: ["Technology", "Innovation", "Science", "Culture"],
    },
    {
        id: "911",
        type: EventType.EVENT,
        title: "September 11 Attacks",
        year: 2001,
        yearDisplay: "2001",
        description: "Terrorist attacks on the World Trade Center.",
        importance: 9,
        tags: ["War", "Politics", "USA"],
    },
    {
        id: "genome",
        type: EventType.SUB_EVENT,
        title: "Human Genome Project",
        year: 2003,
        yearDisplay: "2003",
        description: "Complete mapping of human DNA.",
        importance: 6,
        tags: ["Science", "Biology", "Innovation"],
    },
    {
        id: "facebook",
        type: EventType.SUB_EVENT,
        title: "Facebook Launches",
        year: 2004,
        yearDisplay: "2004",
        description: "Start of the social media era.",
        importance: 6,
        parentId: "info-age",
        tags: ["Technology", "Innovation", "Culture", "Society"],
    },
    {
        id: "iphone",
        type: EventType.EVENT,
        title: "iPhone Released",
        year: 2007,
        yearDisplay: "2007",
        dateDisplay: "June 29th",
        description: "Apple revolutionizes mobile computing.",
        importance: 8,
        parentId: "info-age",
        tags: ["Technology", "Innovation", "Mobile"],
        imageUrl: "https://picsum.photos/seed/iphone/400/600"
    },
    {
        id: "bitcoin",
        type: EventType.SUB_EVENT,
        title: "Bitcoin Created",
        year: 2009,
        yearDisplay: "2009",
        description: "Satoshi Nakamoto mines the genesis block.",
        importance: 6,
        parentId: "info-age",
        tags: ["Finance", "Technology", "Innovation"],
    },
    {
        id: "higgs",
        type: EventType.SUB_EVENT,
        title: "Higgs Boson Discovered",
        year: 2012,
        yearDisplay: "2012",
        description: "CERN confirms existence of the 'God particle'.",
        importance: 5,
        parentId: "info-age",
        tags: ["Science", "Physics"],
    },
    {
        id: "crispr",
        type: EventType.SUB_EVENT,
        title: "CRISPR Gene Editing",
        year: 2012,
        yearDisplay: "2012",
        description: "Doudna and Charpentier publish CRISPR-Cas9 method.",
        importance: 5,
        parentId: "info-age",
        tags: ["Science", "Biology", "Innovation"],
    },
    {
        id: "covid",
        type: EventType.EVENT,
        title: "COVID-19 Pandemic",
        year: 2020,
        yearDisplay: "2020",
        description: "Global lockdown and race for vaccines.",
        importance: 9,
        parentId: "info-age",
        tags: ["Health", "Global", "Science"],
    },
    {
        id: "webb",
        type: EventType.SUB_EVENT,
        title: "James Webb Telescope",
        year: 2021,
        yearDisplay: "2021",
        description: "Launch of the most powerful space telescope.",
        importance: 5,
        parentId: "info-age",
        tags: ["Space", "Technology", "Innovation", "Science"],
    },
    {
        id: "ai-boom",
        type: EventType.EVENT,
        title: "Generative AI Boom",
        year: 2023,
        yearDisplay: "2023",
        description: "Mainstream adoption of LLMs like Gemini.",
        importance: 8,
        parentId: "info-age",
        tags: ["Technology", "AI", "Innovation", "Science"],
        imageUrl: "https://picsum.photos/seed/ai/600/400"
    }
];