import { EventType, HistoricalEvent } from "../types";

const createSourceUrl = (title: string) => `https://grokipedia.com/?q=${encodeURIComponent(title)}`;

export const MOCK_EVENTS: HistoricalEvent[] = [
    // --- COSMIC ORIGINS (13.8 BYA - 4.5 BYA) ---
    {
        id: "cosmic-era",
        type: EventType.ERA,
        title: "The Cosmic Dawn",
        year: -13800000000,
        yearDisplay: "13.8 BYA",
        description: "The birth of the universe and the formation of the first structures.",
        importance: 10,
        tags: ["Cosmic", "Space", "Physics"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6f/CMB_Timeline300_no_WMAP.jpg",
        sourceUrl: createSourceUrl("Big Bang")
    },
    {
        id: "big-bang",
        type: EventType.EVENT,
        title: "The Big Bang",
        year: -13800000000,
        yearDisplay: "13.8 BYA",
        description: "Space and time begin. The universe starts expanding from a singularity.",
        importance: 10,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Space", "Science"],
        sourceUrl: createSourceUrl("Big Bang")
    },
    {
        id: "inflation",
        type: EventType.SUB_EVENT,
        title: "Cosmic Inflation",
        year: -13800000000 + 1, // virtually same time
        yearDisplay: "10⁻³² s after Big Bang",
        description: "The universe expands exponentially, smoothing out irregularities.",
        importance: 6,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Physics"],
        sourceUrl: createSourceUrl("Cosmic inflation")
    },
    {
        id: "recombination",
        type: EventType.EVENT,
        title: "Recombination",
        year: -13800000000 + 380000,
        yearDisplay: "380,000 years after Big Bang",
        description: "The universe cools enough for atoms to form. The Cosmic Microwave Background is released.",
        importance: 8,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Physics"],
        sourceUrl: createSourceUrl("Recombination (cosmology)")
    },
    {
        id: "dark-ages",
        type: EventType.SUB_EVENT,
        title: "Cosmic Dark Ages",
        year: -13700000000,
        yearDisplay: "13.7 BYA",
        description: "The universe is filled with hydrogen and helium, but no stars have ignited yet.",
        importance: 5,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Space"],
        sourceUrl: createSourceUrl("Chronology of the universe")
    },
    {
        id: "first-stars",
        type: EventType.EVENT,
        title: "First Stars Ignite",
        year: -13600000000,
        yearDisplay: "13.6 BYA",
        description: "Population III stars form, ending the cosmic dark ages and reionizing the universe.",
        importance: 9,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Space"],
        sourceUrl: createSourceUrl("Population III stars")
    },
    {
        id: "first-galaxies",
        type: EventType.EVENT,
        title: "Formation of Galaxies",
        year: -13000000000,
        yearDisplay: "13 BYA",
        description: "Gravity pulls matter together to form the first proto-galaxies.",
        importance: 8,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Space"],
        sourceUrl: createSourceUrl("Galaxy formation and evolution")
    },
    {
        id: "milky-way",
        type: EventType.EVENT,
        title: "Birth of the Milky Way",
        year: -12500000000,
        yearDisplay: "12.5 BYA",
        description: "Our home galaxy begins to form from the merger of smaller protogalaxies.",
        importance: 9,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Space"],
        sourceUrl: createSourceUrl("Milky Way")
    },
    {
        id: "solar-nebula",
        type: EventType.SUB_EVENT,
        title: "Solar Nebula Collapse",
        year: -4600000000,
        yearDisplay: "4.6 BYA",
        description: "A molecular cloud collapses to form our Sun and the protoplanetary disk.",
        importance: 7,
        parentId: "cosmic-era",
        tags: ["Cosmic", "Space", "Earth"],
        sourceUrl: createSourceUrl("Formation and evolution of the Solar System")
    },

    // --- PLANETARY & LIFE (4.5 BYA - 500 MYA) ---
    {
        id: "precambrian-era",
        type: EventType.ERA,
        title: "Precambrian Eon",
        year: -4540000000,
        yearDisplay: "4.54 BYA - 541 MYA",
        description: "The formation of Earth and the long evolution of simple life.",
        importance: 10,
        tags: ["Earth", "Biology", "Prehistory"],
        sourceUrl: createSourceUrl("Precambrian")
    },
    {
        id: "earth-formed",
        type: EventType.EVENT,
        title: "Formation of Earth",
        year: -4540000000,
        yearDisplay: "4.54 BYA",
        description: "Earth forms from the accretion of the solar nebula.",
        importance: 9,
        parentId: "precambrian-era",
        tags: ["Cosmic", "Earth", "Space"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Planets2013.svg/1200px-Planets2013.svg.png",
        sourceUrl: createSourceUrl("History of Earth")
    },
    {
        id: "moon-formation",
        type: EventType.EVENT,
        title: "Giant Impact Hypothesis",
        year: -4510000000,
        yearDisplay: "4.51 BYA",
        description: "Theia collides with Earth, creating the Moon.",
        importance: 8,
        parentId: "precambrian-era",
        tags: ["Earth", "Space", "Cosmic"],
        sourceUrl: createSourceUrl("Giant-impact hypothesis")
    },
    {
        id: "late-heavy-bombardment",
        type: EventType.SUB_EVENT,
        title: "Late Heavy Bombardment",
        year: -4100000000,
        yearDisplay: "4.1 BYA",
        description: "A disproportionately large number of asteroids collide with the early terrestrial planets.",
        importance: 6,
        parentId: "precambrian-era",
        tags: ["Space", "Disaster", "Earth"],
        sourceUrl: createSourceUrl("Late Heavy Bombardment")
    },
    {
        id: "first-water",
        type: EventType.SUB_EVENT,
        title: "First Oceans",
        year: -4000000000,
        yearDisplay: "4.0 BYA",
        description: "Earth cools enough for liquid water to condense, forming the first oceans.",
        importance: 7,
        parentId: "precambrian-era",
        tags: ["Earth", "Biology"],
        sourceUrl: createSourceUrl("Origin of water on Earth")
    },
    {
        id: "life-begins",
        type: EventType.EVENT,
        title: "First Life",
        year: -3800000000,
        yearDisplay: "3.8 BYA",
        description: "Simple single-celled organisms (prokaryotes) appear in hydrothermal vents.",
        importance: 9,
        parentId: "precambrian-era",
        tags: ["Biology", "Science"],
        sourceUrl: createSourceUrl("Abiogenesis")
    },
    {
        id: "photosynthesis",
        type: EventType.EVENT,
        title: "Photosynthesis Evolves",
        year: -3400000000,
        yearDisplay: "3.4 BYA",
        description: "Cyanobacteria begin converting sunlight into energy.",
        importance: 8,
        parentId: "precambrian-era",
        tags: ["Biology", "Earth"],
        sourceUrl: createSourceUrl("Evolution of photosynthesis")
    },
    {
        id: "great-oxidation",
        type: EventType.EVENT,
        title: "Great Oxidation Event",
        year: -2400000000,
        yearDisplay: "2.4 BYA",
        description: "Oxygen accumulates in the atmosphere, causing a mass extinction of anaerobes but paving the way for complex life.",
        importance: 8,
        parentId: "precambrian-era",
        tags: ["Biology", "Disaster", "Earth"],
        sourceUrl: createSourceUrl("Great Oxidation Event")
    },
    {
        id: "eukaryotes",
        type: EventType.SUB_EVENT,
        title: "First Eukaryotes",
        year: -1850000000,
        yearDisplay: "1.85 BYA",
        description: "Cells with nuclei appear, likely through endosymbiosis.",
        importance: 7,
        parentId: "precambrian-era",
        tags: ["Biology"],
        sourceUrl: createSourceUrl("Eukaryote")
    },
    {
        id: "multicellular",
        type: EventType.SUB_EVENT,
        title: "Multicellular Life",
        year: -900000000,
        yearDisplay: "900 MYA",
        description: "Organisms begin to bind together.",
        importance: 7,
        parentId: "precambrian-era",
        tags: ["Biology"],
        sourceUrl: createSourceUrl("Multicellular organism")
    },

    // --- PALEOZOIC & MESOZOIC (541 MYA - 66 MYA) ---
    {
        id: "phanerozoic-era",
        type: EventType.ERA,
        title: "Phanerozoic Eon",
        year: -541000000,
        yearDisplay: "541 MYA - Present",
        description: "The current eon, the age of visible life.",
        importance: 10,
        tags: ["Biology", "Earth", "Prehistory"],
        sourceUrl: createSourceUrl("Phanerozoic")
    },
    {
        id: "cambrian-explosion",
        type: EventType.EVENT,
        title: "Cambrian Explosion",
        year: -541000000,
        yearDisplay: "541 MYA",
        description: "Rapid appearance of most major animal phyla.",
        importance: 9,
        parentId: "phanerozoic-era",
        tags: ["Biology", "Prehistory"],
        sourceUrl: createSourceUrl("Cambrian explosion")
    },
    {
        id: "land-plants",
        type: EventType.SUB_EVENT,
        title: "Plants Colonize Land",
        year: -470000000,
        yearDisplay: "470 MYA",
        description: "Life moves from the ocean to the land.",
        importance: 7,
        parentId: "phanerozoic-era",
        tags: ["Biology", "Earth"],
        sourceUrl: createSourceUrl("Evolutionary history of plants")
    },
    {
        id: "permian-extinction",
        type: EventType.EVENT,
        title: "The Great Dying",
        year: -252000000,
        yearDisplay: "252 MYA",
        description: "Permian-Triassic extinction event kills 96% of marine species.",
        importance: 9,
        parentId: "phanerozoic-era",
        tags: ["Disaster", "Prehistory", "Earth"],
        sourceUrl: createSourceUrl("Permian–Triassic extinction event")
    },
    {
        id: "dinosaurs-appear",
        type: EventType.EVENT,
        title: "Age of Dinosaurs",
        year: -230000000,
        yearDisplay: "230 MYA",
        description: "Dinosaurs evolve and begin to dominate the planet.",
        importance: 8,
        parentId: "phanerozoic-era",
        tags: ["Prehistory", "Biology"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Tyrannosaurus_rex_mmartyniuk.png",
        sourceUrl: createSourceUrl("Dinosaur")
    },
    {
        id: "mammals-appear",
        type: EventType.SUB_EVENT,
        title: "First Mammals",
        year: -200000000,
        yearDisplay: "200 MYA",
        description: "Small, shrew-like mammals appear alongside dinosaurs.",
        importance: 6,
        parentId: "phanerozoic-era",
        tags: ["Biology", "Prehistory"],
        sourceUrl: createSourceUrl("Evolution of mammals")
    },
    {
        id: "flowers",
        type: EventType.SUB_EVENT,
        title: "First Flowering Plants",
        year: -130000000,
        yearDisplay: "130 MYA",
        description: "Angiosperms evolve, changing the face of the planet.",
        importance: 6,
        parentId: "phanerozoic-era",
        tags: ["Biology"],
        sourceUrl: createSourceUrl("Flowering plant")
    },
    {
        id: "dinosaurs-extinct",
        type: EventType.EVENT,
        title: "K-Pg Extinction",
        year: -66000000,
        yearDisplay: "66 MYA",
        description: "Asteroid impact wipes out non-avian dinosaurs.",
        importance: 9,
        parentId: "phanerozoic-era",
        tags: ["Prehistory", "Earth", "Disaster"],
        sourceUrl: createSourceUrl("Cretaceous–Paleogene extinction event")
    },

    // --- HUMAN PREHISTORY ---
    {
        id: "human-prehistory",
        type: EventType.ERA,
        title: "Human Prehistory",
        year: -300000,
        yearDisplay: "300,000 BC - 3200 BC",
        description: "The evolution of humans and the Stone Age.",
        importance: 9,
        tags: ["Anthropology", "Prehistory", "Society"],
        sourceUrl: createSourceUrl("Prehistory")
    },
    {
        id: "homo-sapiens",
        type: EventType.EVENT,
        title: "Homo Sapiens Emerge",
        year: -300000,
        yearDisplay: "300,000 BC",
        description: "Anatomically modern humans evolve in Africa.",
        importance: 9,
        parentId: "human-prehistory",
        tags: ["Anthropology", "Biology"],
        sourceUrl: createSourceUrl("Early modern human")
    },
    {
        id: "fire-control",
        type: EventType.SUB_EVENT,
        title: "Control of Fire",
        year: -400000, // Debatable, but widespread by early humans
        yearDisplay: "400,000 BC",
        description: "Early humans learn to control fire for cooking and warmth.",
        importance: 8,
        parentId: "human-prehistory",
        tags: ["Technology", "Anthropology"],
        sourceUrl: createSourceUrl("Control of fire by early humans")
    },
    {
        id: "out-of-africa",
        type: EventType.EVENT,
        title: "Migration out of Africa",
        year: -60000,
        yearDisplay: "60,000 BC",
        description: "Humans begin to spread to Eurasia and Australia.",
        importance: 8,
        parentId: "human-prehistory",
        tags: ["Anthropology", "Exploration"],
        sourceUrl: createSourceUrl("Early human migrations")
    },
    {
        id: "agriculture",
        type: EventType.EVENT,
        title: "Agricultural Revolution",
        year: -10000,
        yearDisplay: "10,000 BC",
        description: "Humans begin farming and domesticating animals.",
        importance: 9,
        parentId: "human-prehistory",
        tags: ["Society", "Technology"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Diorama%2C_cave_men_-_National_Museum_of_Nature_and_Science%2C_Tokyo_-_DSC07368.JPG/1280px-Diorama%2C_cave_men_-_National_Museum_of_Nature_and_Science%2C_Tokyo_-_DSC07368.JPG",
        sourceUrl: createSourceUrl("Neolithic Revolution")
    },
    {
        id: "wheel",
        type: EventType.SUB_EVENT,
        title: "Invention of the Wheel",
        year: -3500,
        yearDisplay: "3500 BC",
        description: "The wheel is invented in Mesopotamia.",
        importance: 7,
        parentId: "human-prehistory",
        tags: ["Technology", "Innovation"],
        sourceUrl: createSourceUrl("Wheel")
    },
    {
        id: "writing",
        type: EventType.EVENT,
        title: "Invention of Writing",
        year: -3200,
        yearDisplay: "3200 BC",
        description: "Cuneiform script emerges in Sumer.",
        importance: 9,
        parentId: "human-prehistory",
        tags: ["Culture", "Technology"],
        sourceUrl: createSourceUrl("History of writing")
    },

    // --- ANCIENT HISTORY (3200 BC - 500 AD) ---
    {
        id: "classical-era",
        type: EventType.ERA,
        title: "Classical Antiquity",
        year: -800,
        yearDisplay: "800 BC - 500 AD",
        description: "The era of Greek and Roman dominance.",
        importance: 10,
        tags: ["History", "Politics", "Culture"],
        sourceUrl: createSourceUrl("Classical antiquity")
    },
    {
        id: "pyramids",
        type: EventType.EVENT,
        title: "Great Pyramid of Giza",
        year: -2560,
        yearDisplay: "2560 BC",
        description: "Completion of the Great Pyramid for Pharaoh Khufu.",
        importance: 8,
        tags: ["Architecture", "Egypt"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Kheops-Pyramid.jpg",
        sourceUrl: createSourceUrl("Great Pyramid of Giza")
    },
    {
        id: "hammurabi",
        type: EventType.SUB_EVENT,
        title: "Code of Hammurabi",
        year: -1754,
        yearDisplay: "1754 BC",
        description: "One of the earliest and most complete written legal codes.",
        importance: 6,
        tags: ["Law", "Politics", "History"],
        sourceUrl: createSourceUrl("Code of Hammurabi")
    },
    {
        id: "bronze-collapse",
        type: EventType.EVENT,
        title: "Bronze Age Collapse",
        year: -1177,
        yearDisplay: "1177 BC",
        description: "Sudden collapse of major civilizations in the Mediterranean.",
        importance: 8,
        tags: ["Disaster", "History", "War"],
        sourceUrl: createSourceUrl("Late Bronze Age collapse")
    },
    {
        id: "rome-founded",
        type: EventType.EVENT,
        title: "Founding of Rome",
        year: -753,
        yearDisplay: "753 BC",
        description: "Legendary founding of Rome by Romulus and Remus.",
        importance: 8,
        parentId: "classical-era",
        tags: ["Politics", "Rome"],
        sourceUrl: createSourceUrl("Founding of Rome")
    },
    {
        id: "buddhism",
        type: EventType.SUB_EVENT,
        title: "Birth of Buddhism",
        year: -563,
        yearDisplay: "563 BC",
        description: "Siddhartha Gautama is born in Lumbini.",
        importance: 6,
        parentId: "classical-era",
        tags: ["Religion", "Philosophy"],
        sourceUrl: createSourceUrl("Buddhism")
    },
    {
        id: "democracy",
        type: EventType.EVENT,
        title: "Athenian Democracy",
        year: -508,
        yearDisplay: "508 BC",
        description: "Cleisthenes introduces democratic reforms.",
        importance: 7,
        parentId: "classical-era",
        tags: ["Politics", "Greece"],
        sourceUrl: createSourceUrl("Athenian democracy")
    },
    {
        id: "marathon",
        type: EventType.SUB_EVENT,
        title: "Battle of Marathon",
        year: -490,
        yearDisplay: "490 BC",
        description: "Greeks defeat the Persian invasion.",
        importance: 6,
        parentId: "classical-era",
        tags: ["War", "Greece"],
        sourceUrl: createSourceUrl("Battle of Marathon")
    },
    {
        id: "alexander",
        type: EventType.EVENT,
        title: "Alexander the Great",
        year: -336,
        yearDisplay: "336 BC",
        description: "Alexander begins his conquests, creating a vast empire.",
        importance: 9,
        parentId: "classical-era",
        tags: ["War", "Politics", "Greece"],
        sourceUrl: createSourceUrl("Alexander the Great")
    },
    {
        id: "great-wall",
        type: EventType.EVENT,
        title: "Great Wall of China",
        year: -221,
        yearDisplay: "221 BC",
        description: "Qin Shi Huang begins unifying the walls of China.",
        importance: 8,
        tags: ["China", "Architecture"],
        sourceUrl: createSourceUrl("Great Wall of China")
    },
    {
        id: "caesar-death",
        type: EventType.EVENT,
        title: "Assassination of Caesar",
        year: -44,
        yearDisplay: "44 BC",
        dateDisplay: "March 15th",
        description: "Julius Caesar is stabbed to death.",
        importance: 8,
        parentId: "classical-era",
        tags: ["Politics", "Rome", "War"],
        sourceUrl: createSourceUrl("Assassination of Julius Caesar")
    },
    {
        id: "jesus",
        type: EventType.EVENT,
        title: "Life of Jesus",
        year: 30, // Approx
        yearDisplay: "30 AD",
        description: "Crucifixion of Jesus and rise of Christianity.",
        importance: 9,
        parentId: "classical-era",
        tags: ["Religion", "Culture"],
        sourceUrl: createSourceUrl("Jesus")
    },
    {
        id: "pompeii",
        type: EventType.SUB_EVENT,
        title: "Eruption of Vesuvius",
        year: 79,
        yearDisplay: "79 AD",
        description: "Pompeii is destroyed by volcanic ash.",
        importance: 6,
        parentId: "classical-era",
        tags: ["Disaster", "Rome"],
        sourceUrl: createSourceUrl("Eruption of Mount Vesuvius in 79 AD")
    },

    // --- MIDDLE AGES (476 - 1450) ---
    {
        id: "middle-ages",
        type: EventType.ERA,
        title: "The Middle Ages",
        year: 476,
        yearDisplay: "476 - 1450",
        description: "Fall of Rome to the Renaissance.",
        importance: 10,
        tags: ["History", "Europe", "Religion"],
        sourceUrl: createSourceUrl("Middle Ages")
    },
    {
        id: "rome-fall",
        type: EventType.EVENT,
        title: "Fall of Western Rome",
        year: 476,
        yearDisplay: "476 AD",
        description: "Romulus Augustulus is deposed.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["Politics", "Rome"],
        sourceUrl: createSourceUrl("Fall of the Western Roman Empire")
    },
    {
        id: "justinian",
        type: EventType.SUB_EVENT,
        title: "Justinian Code",
        year: 529,
        yearDisplay: "529 AD",
        description: "Codification of Roman law.",
        importance: 6,
        parentId: "middle-ages",
        tags: ["Law", "Politics"],
        sourceUrl: createSourceUrl("Corpus Juris Civilis")
    },
    {
        id: "islam-founding",
        type: EventType.EVENT,
        title: "Founding of Islam",
        year: 610,
        yearDisplay: "610 AD",
        description: "Muhammad receives his first revelation.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["Religion"],
        sourceUrl: createSourceUrl("Muhammad")
    },
    {
        id: "vikings",
        type: EventType.EVENT,
        title: "Viking Age Begins",
        year: 793,
        yearDisplay: "793 AD",
        description: "Vikings raid Lindisfarne.",
        importance: 7,
        parentId: "middle-ages",
        tags: ["War", "Europe", "Exploration"],
        sourceUrl: createSourceUrl("Viking Age")
    },
    {
        id: "charlemagne",
        type: EventType.EVENT,
        title: "Charlemagne Crowned",
        year: 800,
        yearDisplay: "800 AD",
        description: "First Holy Roman Emperor.",
        importance: 8,
        parentId: "middle-ages",
        tags: ["Politics", "Europe"],
        sourceUrl: createSourceUrl("Charlemagne")
    },
    {
        id: "gunpowder",
        type: EventType.SUB_EVENT,
        title: "Invention of Gunpowder",
        year: 850,
        yearDisplay: "850 AD",
        description: "Chinese alchemists discover gunpowder.",
        importance: 8,
        parentId: "middle-ages",
        tags: ["Technology", "War"],
        sourceUrl: createSourceUrl("History of gunpowder")
    },
    {
        id: "schism",
        type: EventType.SUB_EVENT,
        title: "Great Schism",
        year: 1054,
        yearDisplay: "1054",
        description: "Split between Catholic and Orthodox Church.",
        importance: 6,
        parentId: "middle-ages",
        tags: ["Religion", "Politics"],
        sourceUrl: createSourceUrl("East–West Schism")
    },
    {
        id: "hastings",
        type: EventType.EVENT,
        title: "Battle of Hastings",
        year: 1066,
        yearDisplay: "1066",
        description: "Norman conquest of England.",
        importance: 8,
        parentId: "middle-ages",
        tags: ["War", "UK"],
        sourceUrl: createSourceUrl("Battle of Hastings")
    },
    {
        id: "universities",
        type: EventType.SUB_EVENT,
        title: "First University",
        year: 1088,
        yearDisplay: "1088",
        description: "University of Bologna founded.",
        importance: 6,
        parentId: "middle-ages",
        tags: ["Education"],
        sourceUrl: createSourceUrl("University of Bologna")
    },
    {
        id: "crusades",
        type: EventType.EVENT,
        title: "First Crusade",
        year: 1096,
        yearDisplay: "1096",
        description: "Christian Europe attempts to reclaim the Holy Land.",
        importance: 8,
        parentId: "middle-ages",
        tags: ["War", "Religion"],
        sourceUrl: createSourceUrl("First Crusade")
    },
    {
        id: "genghis",
        type: EventType.EVENT,
        title: "Mongol Empire",
        year: 1206,
        yearDisplay: "1206",
        description: "Genghis Khan unites the tribes.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["War", "Asia"],
        sourceUrl: createSourceUrl("Mongol Empire")
    },
    {
        id: "magna-carta",
        type: EventType.SUB_EVENT,
        title: "Magna Carta",
        year: 1215,
        yearDisplay: "1215",
        description: "King John signs the Great Charter.",
        importance: 7,
        parentId: "middle-ages",
        tags: ["Politics", "Law"],
        sourceUrl: createSourceUrl("Magna Carta")
    },
    {
        id: "black-death",
        type: EventType.EVENT,
        title: "The Black Death",
        year: 1347,
        yearDisplay: "1347",
        description: "Plague kills 30-60% of Europe.",
        importance: 9,
        parentId: "middle-ages",
        tags: ["Health", "Disaster"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Black_Death.jpg",
        sourceUrl: createSourceUrl("Black Death")
    },

    // --- EARLY MODERN (1450 - 1750) ---
    {
        id: "early-modern",
        type: EventType.ERA,
        title: "Early Modern Period",
        year: 1450,
        yearDisplay: "1450 - 1750",
        description: "Renaissance, Reformation, and Discovery.",
        importance: 10,
        tags: ["Art", "Science", "Exploration"],
        sourceUrl: createSourceUrl("Early modern period")
    },
    {
        id: "printing-press",
        type: EventType.EVENT,
        title: "Printing Press",
        year: 1440,
        yearDisplay: "1440",
        description: "Gutenberg invents movable type.",
        importance: 9,
        parentId: "early-modern",
        tags: ["Technology", "Innovation"],
        sourceUrl: createSourceUrl("Printing press")
    },
    {
        id: "constantinople",
        type: EventType.SUB_EVENT,
        title: "Fall of Constantinople",
        year: 1453,
        yearDisplay: "1453",
        description: "Ottoman Empire captures the city, ending Byzantine Empire.",
        importance: 7,
        parentId: "early-modern",
        tags: ["War", "Politics"],
        sourceUrl: createSourceUrl("Fall of Constantinople")
    },
    {
        id: "columbus",
        type: EventType.EVENT,
        title: "Voyage of Columbus",
        year: 1492,
        yearDisplay: "1492",
        description: "Columbus arrives in the Americas.",
        importance: 9,
        parentId: "early-modern",
        tags: ["Exploration"],
        sourceUrl: createSourceUrl("Christopher Columbus")
    },
    {
        id: "reformation",
        type: EventType.EVENT,
        title: "The Reformation",
        year: 1517,
        yearDisplay: "1517",
        description: "Luther posts 95 Theses.",
        importance: 8,
        parentId: "early-modern",
        tags: ["Religion"],
        sourceUrl: createSourceUrl("Reformation")
    },
    {
        id: "copernicus",
        type: EventType.SUB_EVENT,
        title: "Heliocentric Theory",
        year: 1543,
        yearDisplay: "1543",
        description: "Sun-centered model of the universe.",
        importance: 7,
        parentId: "early-modern",
        tags: ["Science", "Space"],
        sourceUrl: createSourceUrl("Nicolaus Copernicus")
    },
    {
        id: "armada",
        type: EventType.SUB_EVENT,
        title: "Spanish Armada",
        year: 1588,
        yearDisplay: "1588",
        description: "Defeat of the Spanish fleet by England.",
        importance: 6,
        parentId: "early-modern",
        tags: ["War", "UK", "Spain"],
        sourceUrl: createSourceUrl("Spanish Armada")
    },
    {
        id: "galileo",
        type: EventType.SUB_EVENT,
        title: "Galileo's Telescope",
        year: 1609,
        yearDisplay: "1609",
        description: "First astronomical observations.",
        importance: 7,
        parentId: "early-modern",
        tags: ["Science", "Space"],
        sourceUrl: createSourceUrl("Galileo Galilei")
    },
    {
        id: "newton",
        type: EventType.EVENT,
        title: "Principia Mathematica",
        year: 1687,
        yearDisplay: "1687",
        description: "Newton publishes laws of motion.",
        importance: 8,
        parentId: "early-modern",
        tags: ["Science", "Physics"],
        sourceUrl: createSourceUrl("Philosophiæ Naturalis Principia Mathematica")
    },

    // --- REVOLUTIONS & INDUSTRY (1750 - 1900) ---
    {
        id: "industrial-era",
        type: EventType.ERA,
        title: "Age of Revolution",
        year: 1760,
        yearDisplay: "1760 - 1900",
        description: "Industrial, Political, and Social Revolutions.",
        importance: 10,
        tags: ["Industry", "Politics", "Technology"],
        sourceUrl: createSourceUrl("Age of Revolution")
    },
    {
        id: "steam-engine",
        type: EventType.EVENT,
        title: "Watt Steam Engine",
        year: 1769,
        yearDisplay: "1769",
        description: "James Watt improves the steam engine.",
        importance: 9,
        parentId: "industrial-era",
        tags: ["Technology", "Industry"],
        sourceUrl: createSourceUrl("Watt steam engine")
    },
    {
        id: "us-independence",
        type: EventType.EVENT,
        title: "US Independence",
        year: 1776,
        yearDisplay: "1776",
        description: "Declaration of Independence signed.",
        importance: 9,
        parentId: "industrial-era",
        tags: ["Politics", "USA"],
        sourceUrl: createSourceUrl("United States Declaration of Independence")
    },
    {
        id: "french-rev",
        type: EventType.EVENT,
        title: "French Revolution",
        year: 1789,
        yearDisplay: "1789",
        description: "Storming of the Bastille.",
        importance: 9,
        parentId: "industrial-era",
        tags: ["Politics", "France"],
        sourceUrl: createSourceUrl("French Revolution")
    },
    {
        id: "vaccine",
        type: EventType.SUB_EVENT,
        title: "First Vaccine",
        year: 1796,
        yearDisplay: "1796",
        description: "Edward Jenner treats smallpox.",
        importance: 7,
        parentId: "industrial-era",
        tags: ["Health", "Science"],
        sourceUrl: createSourceUrl("Edward Jenner")
    },
    {
        id: "telegraph",
        type: EventType.SUB_EVENT,
        title: "Electric Telegraph",
        year: 1837,
        yearDisplay: "1837",
        description: "Communication revolution.",
        importance: 7,
        parentId: "industrial-era",
        tags: ["Technology", "Comms"],
        sourceUrl: createSourceUrl("Electrical telegraph")
    },
    {
        id: "darwin",
        type: EventType.EVENT,
        title: "Origin of Species",
        year: 1859,
        yearDisplay: "1859",
        description: "Darwin proposes evolution by natural selection.",
        importance: 9,
        parentId: "industrial-era",
        tags: ["Science", "Biology"],
        sourceUrl: createSourceUrl("On the Origin of Species")
    },
    {
        id: "civil-war",
        type: EventType.EVENT,
        title: "US Civil War",
        year: 1861,
        yearDisplay: "1861",
        description: "Union vs Confederacy.",
        importance: 8,
        parentId: "industrial-era",
        tags: ["War", "USA"],
        sourceUrl: createSourceUrl("American Civil War")
    },
    {
        id: "telephone",
        type: EventType.SUB_EVENT,
        title: "Telephone Invented",
        year: 1876,
        yearDisplay: "1876",
        description: "Bell patents the telephone.",
        importance: 7,
        parentId: "industrial-era",
        tags: ["Technology", "Comms"],
        sourceUrl: createSourceUrl("Invention of the telephone")
    },
    {
        id: "lightbulb",
        type: EventType.EVENT,
        title: "Electric Light",
        year: 1879,
        yearDisplay: "1879",
        description: "Edison creates practical incandescent light.",
        importance: 9,
        parentId: "industrial-era",
        tags: ["Technology"],
        sourceUrl: createSourceUrl("Incandescent light bulb")
    },
    {
        id: "car",
        type: EventType.EVENT,
        title: "First Automobile",
        year: 1886,
        yearDisplay: "1886",
        description: "Benz Patent-Motorwagen.",
        importance: 8,
        parentId: "industrial-era",
        tags: ["Technology", "Transport"],
        sourceUrl: createSourceUrl("Benz Patent-Motorwagen")
    },

    // --- 20TH CENTURY (1900 - 2000) ---
    {
        id: "modern-era",
        type: EventType.ERA,
        title: "The 20th Century",
        year: 1900,
        yearDisplay: "1900 - 1999",
        description: "Wars, Technology, and Civil Rights.",
        importance: 10,
        tags: ["History", "War", "Technology"],
        sourceUrl: createSourceUrl("20th century")
    },
    {
        id: "flight",
        type: EventType.EVENT,
        title: "First Flight",
        year: 1903,
        yearDisplay: "1903",
        description: "Wright Brothers fly.",
        importance: 9,
        parentId: "modern-era",
        tags: ["Technology", "Aviation"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/First_flight2.jpg/1200px-First_flight2.jpg",
        sourceUrl: createSourceUrl("Wright brothers")
    },
    {
        id: "einstein",
        type: EventType.SUB_EVENT,
        title: "Theory of Relativity",
        year: 1905,
        yearDisplay: "1905",
        description: "Einstein changes physics.",
        importance: 8,
        parentId: "modern-era",
        tags: ["Science", "Physics"],
        sourceUrl: createSourceUrl("Theory of relativity")
    },
    {
        id: "ww1",
        type: EventType.EVENT,
        title: "World War I",
        year: 1914,
        yearDisplay: "1914 - 1918",
        description: "The Great War.",
        importance: 9,
        parentId: "modern-era",
        tags: ["War"],
        sourceUrl: createSourceUrl("World War I")
    },
    {
        id: "russian-rev",
        type: EventType.SUB_EVENT,
        title: "Russian Revolution",
        year: 1917,
        yearDisplay: "1917",
        description: "Rise of the Soviet Union.",
        importance: 7,
        parentId: "modern-era",
        tags: ["Politics"],
        sourceUrl: createSourceUrl("Russian Revolution")
    },
    {
        id: "penicillin",
        type: EventType.EVENT,
        title: "Penicillin Discovered",
        year: 1928,
        yearDisplay: "1928",
        description: "First antibiotic.",
        importance: 8,
        parentId: "modern-era",
        tags: ["Health", "Science"],
        sourceUrl: createSourceUrl("Penicillin")
    },
    {
        id: "ww2",
        type: EventType.EVENT,
        title: "World War II",
        year: 1939,
        yearDisplay: "1939 - 1945",
        description: "Global conflict.",
        importance: 10,
        parentId: "modern-era",
        tags: ["War"],
        sourceUrl: createSourceUrl("World War II")
    },
    {
        id: "d-day",
        type: EventType.SUB_EVENT,
        title: "D-Day",
        year: 1944,
        yearDisplay: "1944",
        description: "Allied invasion of Normandy.",
        importance: 7,
        parentId: "modern-era",
        tags: ["War"],
        sourceUrl: createSourceUrl("Normandy landings")
    },
    {
        id: "atomic-bomb",
        type: EventType.EVENT,
        title: "Atomic Bomb",
        year: 1945,
        yearDisplay: "1945",
        description: "Hiroshima and Nagasaki.",
        importance: 9,
        parentId: "modern-era",
        tags: ["War", "Technology"],
        sourceUrl: createSourceUrl("Atomic bombings of Hiroshima and Nagasaki")
    },
    {
        id: "cold-war-start",
        type: EventType.SUB_EVENT,
        title: "Cold War Begins",
        year: 1947,
        yearDisplay: "1947",
        description: "Tension between USA and USSR.",
        importance: 7,
        parentId: "modern-era",
        tags: ["Politics"],
        sourceUrl: createSourceUrl("Cold War")
    },
    {
        id: "dna",
        type: EventType.EVENT,
        title: "Structure of DNA",
        year: 1953,
        yearDisplay: "1953",
        description: "Double helix discovered.",
        importance: 8,
        parentId: "modern-era",
        tags: ["Science", "Biology"],
        sourceUrl: createSourceUrl("DNA")
    },
    {
        id: "moon-landing",
        type: EventType.EVENT,
        title: "Moon Landing",
        year: 1969,
        yearDisplay: "1969",
        description: "One small step for man.",
        importance: 10,
        parentId: "modern-era",
        tags: ["Space", "Technology", "USA"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/98/Aldrin_Apollo_11_original.jpg",
        sourceUrl: createSourceUrl("Apollo 11")
    },
    {
        id: "internet",
        type: EventType.EVENT,
        title: "The Internet",
        year: 1983,
        yearDisplay: "1983",
        description: "TCP/IP adopted.",
        importance: 9,
        parentId: "modern-era",
        tags: ["Technology", "Comms"],
        sourceUrl: createSourceUrl("Internet")
    },
    {
        id: "berlin-wall",
        type: EventType.EVENT,
        title: "Fall of Berlin Wall",
        year: 1989,
        yearDisplay: "1989",
        description: "End of the Cold War near.",
        importance: 8,
        parentId: "modern-era",
        tags: ["Politics"],
        sourceUrl: createSourceUrl("Fall of the Berlin Wall")
    },
    {
        id: "web",
        type: EventType.EVENT,
        title: "World Wide Web",
        year: 1991,
        yearDisplay: "1991",
        description: "Public access to the web.",
        importance: 9,
        parentId: "modern-era",
        tags: ["Technology"],
        sourceUrl: createSourceUrl("World Wide Web")
    },

    // --- 21ST CENTURY (2000 - Present) ---
    {
        id: "info-age",
        type: EventType.ERA,
        title: "The Information Age",
        year: 2000,
        yearDisplay: "2000 - Present",
        description: "Digital revolution.",
        importance: 10,
        tags: ["Technology", "Culture"],
        sourceUrl: createSourceUrl("Information Age")
    },
    {
        id: "911",
        type: EventType.EVENT,
        title: "9/11 Attacks",
        year: 2001,
        yearDisplay: "2001",
        description: "Terrorist attacks in USA.",
        importance: 8,
        parentId: "info-age",
        tags: ["War", "Politics", "USA"],
        sourceUrl: createSourceUrl("September 11 attacks")
    },
    {
        id: "genome",
        type: EventType.SUB_EVENT,
        title: "Human Genome Project",
        year: 2003,
        yearDisplay: "2003",
        description: "DNA mapped.",
        importance: 7,
        parentId: "info-age",
        tags: ["Science", "Biology"],
        sourceUrl: createSourceUrl("Human Genome Project")
    },
    {
        id: "iphone",
        type: EventType.EVENT,
        title: "iPhone Released",
        year: 2007,
        yearDisplay: "2007",
        description: "Smartphone revolution.",
        importance: 8,
        parentId: "info-age",
        tags: ["Technology", "Mobile"],
        sourceUrl: createSourceUrl("iPhone")
    },
    {
        id: "higgs",
        type: EventType.SUB_EVENT,
        title: "Higgs Boson",
        year: 2012,
        yearDisplay: "2012",
        description: "Particle discovered at CERN.",
        importance: 6,
        parentId: "info-age",
        tags: ["Science", "Physics"],
        sourceUrl: createSourceUrl("Higgs boson")
    },
    {
        id: "grav-waves",
        type: EventType.SUB_EVENT,
        title: "Gravitational Waves",
        year: 2015,
        yearDisplay: "2015",
        description: "Ripples in spacetime detected.",
        importance: 6,
        parentId: "info-age",
        tags: ["Science", "Physics"],
        sourceUrl: createSourceUrl("Gravitational wave")
    },
    {
        id: "covid",
        type: EventType.EVENT,
        title: "COVID-19 Pandemic",
        year: 2020,
        yearDisplay: "2020",
        description: "Global pandemic.",
        importance: 9,
        parentId: "info-age",
        tags: ["Health", "Global"],
        sourceUrl: createSourceUrl("COVID-19 pandemic")
    },
    {
        id: "webb",
        type: EventType.SUB_EVENT,
        title: "James Webb Telescope",
        year: 2021,
        yearDisplay: "2021",
        description: "Deep space observation.",
        importance: 7,
        parentId: "info-age",
        tags: ["Space", "Technology"],
        sourceUrl: createSourceUrl("James Webb Space Telescope")
    },
    {
        id: "ai-boom",
        type: EventType.EVENT,
        title: "Generative AI",
        year: 2023,
        yearDisplay: "2023",
        description: "AI becomes mainstream.",
        importance: 8,
        parentId: "info-age",
        tags: ["Technology", "AI"],
        sourceUrl: createSourceUrl("Generative artificial intelligence")
    }
];